# Generated by Django 6.0.3 on 2026-04-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Brand'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='sneaker',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sneaker',
            name='size',
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sneakers_img/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Model Name'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
