# Generated by Django 6.0.3 on 2026-04-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_subcategory_sneaker_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Subcategories'},
        ),
    ]
