# Generated by Django 6.0.3 on 2026-04-09 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_subcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
