# Generated by Django 6.0.3 on 2026-04-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Size')),
            ],
        ),
        migrations.AddField(
            model_name='sneaker',
            name='sizes',
            field=models.ManyToManyField(to='store.size', verbose_name='Available Sizes'),
        ),
    ]
