# Generated by Django 6.0.3 on 2026-04-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_size_sneaker_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='store.size', verbose_name='Available Sizes'),
        ),
    ]
